import Head from 'next/head'
import styles from '@styles/Home.module.css'
import { useState } from 'react'
import VideoPreview from '@components/VideoPreview'
import ModalVideo from 'react-modal-video'
import { useRouter } from 'next/router'
import useVideos from '@hooks/useVideos'

export default function Home() {
  const router = useRouter()
  const videoId = router?.query?.videoId
  const [searchTerm, setSearchTerm] = useState('')
  const results = useVideos(searchTerm)

  return (
    <div className={styles.container}>
      <Head>
        {/* eslint-disable-next-line react/no-unescaped-entities */}
        <title>Sandy's Home Videos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className={styles.main}>
        <input
          placeholder="Enter search"
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
        />

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3 w-full">
          {results.map((result) => (
            <VideoPreview videoId={result.item.id} key={result.item.id} />
          ))}
        </div>
        <ModalVideo
          channel="custom"
          isOpen={!!videoId}
          url={`https://sandyshomevideos.s3.amazonaws.com/videos/${videoId}.mp4`}
          onClose={() => router.replace('/', undefined, { shallow: true })}
        />
      </main>
    </div>
  )
}
